fix: replaces travis with gh actions for v34
dhis2/capture-app pull request #1256
Opened 2020-12-01 13:35 UTC by paschalidi

2020-12-01 14:20 UTC, varl requested changes

2020-12-01 14:20 UTC, varl commented on .github/workflows/verify-app.yml
> +          build-dir: build/app
In v34 I think this needs to be `build-dir: build` because it is before the app-platform port.

2020-12-01 14:20 UTC, varl commented on .github/workflows/verify-app.yml
> +          build-dir: build/app
Compare:

https://github.com/d2-ci/capture-app/tree/master
https://github.com/d2-ci/capture-app/tree/v35

and

https://github.com/d2-ci/capture-app/tree/cp/v34/ci/replace-travis

2020-12-01 14:43 UTC, varl approved these changes
LGTM :tada:

2020-12-02 08:28 UTC, JoakimSM approved these changes

2020-12-02 08:28 UTC, merged