fix: [DHIS2-13190] tei geometry
dhis2/capture-app pull request #2808
Opened 2022-05-23 09:38 UTC by simonadomnisoru

2022-07-04 11:11 UTC, superskip requested changes
Hi! Looks like most of the volume in this PR is due to adding line breaks in comma separated list, which I guess is fine. Got a couple of comments. The largest comment asks you to add a lookup table somewhere, I have left it to you to decide the specifics of where and how.

2022-07-05 11:58 UTC, simonadomnisoru commented on src/core_modules/capture-core/components/WidgetProfile/DataEntry/FormFoundation/RenderFoundation.js
> +    programSection.trackedEntityAttributes.reduce((acc, { id }) => [...acc, id], []);
Good catch! I changed it to `map`.

2022-07-05 11:58 UTC, simonadomnisoru commented on src/core_modules/capture-core/components/WidgetProfile/DataEntry/hooks/useGeometryValues.js
> +            setClientValues({ [`FEATURETYPE_${featureType}`]: clientValue });
Sure, I implemented a lookup table for the geometry features logic. Thank you for the suggestion! 😄

2022-07-05 13:24 UTC, superskip reviewed
Looks good! :+1:

2022-07-06 09:20 UTC, simonadomnisoru commented on src/core_modules/capture-core/components/WidgetProfile/DataEntry/helpers/geometry.js
> +};
Hey, 
In the end, it seemed easier and cleaner to merge all the values into a single const object. I also added the flow types. 
Thanks!

2022-07-06 11:10 UTC, superskip reviewed
Hey! I found more to comment on.. This is the third cycle on the same PR, I hope that does not mean I will never be satisfied :stuck_out_tongue:

2022-07-06 11:20 UTC, simonadomnisoru commented on src/core_modules/capture-core/components/WidgetProfile/DataEntry/FormFoundation/DataElement.js
> -        dataEntry.id = `FEATURETYPE_${featureType}`;
Hey,

As I explained in https://github.com/dhis2/capture-app/pull/2808#discussion_r914718990 the `WidgetProfile` is self-contained, that is why the definition of `GEOMETRY` have to be inside the folder. 
IMHO optimizations for other parts of the app are out of scope for this ticket. 
Thanks!

2022-07-06 13:17 UTC, superskip commented on src/core_modules/capture-core/components/WidgetProfile/DataEntry/helpers/geometry.js
> +        FEATURETYPE: 'FEATURETYPE_POINT',
It makes sense then, I suppose. The widgets will all depend on the tracker API though, and therefore _could_ import from some common module defining this dependency. I believe no such module has been made yet however, and that is definitely not part of this ticket to introduce.

2022-07-14 06:27 UTC, geethaalwan approved these changes
Tested successfully on 2.39 and 2.38.2 versions

2022-07-14 07:09 UTC, merged