feat: [DHIS2-14125] improve no saved list
dhis2/capture-app pull request #3132
Opened 2022-11-30 08:25 UTC by jasminenguyennn

2022-12-01 07:48 UTC, cooper-joe commented on src/core_modules/capture-core/components/Pages/Search/TemplateSelector/TemplateSelector.component.js
> +                        {i18n.t('Saved list offer quick access to your most used views in a program.')}
```suggestion
                        {i18n.t('Saved lists offer quick access to your most used views in a program.')}
```

2022-12-01 07:49 UTC, cooper-joe requested changes

2022-12-01 07:49 UTC, cooper-joe commented on src/core_modules/capture-core/components/Pages/Search/TemplateSelector/TemplateSelector.component.js
> +                            {i18n.t('There are no saved list in this program yet, create one using the button below.')}
```suggestion
                            {i18n.t('There are no saved lists in this program yet, create one using the button below.')}
```

2022-12-01 07:49 UTC, cooper-joe commented on src/core_modules/capture-core/components/Pages/Search/TemplateSelector/TemplateSelector.component.js
> +                        {i18n.t('Saved list offer quick access to your most used views in a program.')}
```suggestion
                        {i18n.t('Saved lists offer quick access to your most used views in a program.')}
```

2022-12-01 07:49 UTC, cooper-joe commented on i18n/en.pot
> +msgstr "Saved list offer quick access to your most used views in a program."
```suggestion
msgid "Saved lists offer quick access to your most used views in a program."
msgstr "Saved lists offer quick access to your most used views in a program."
```

2022-12-01 07:49 UTC, cooper-joe commented on i18n/en.pot
> +"below."
```suggestion
"There are no saved lists in this program yet, create one using the button "
"below."
msgstr ""
"There are no saved lists in this program yet, create one using the button "
"below."
```

2022-12-02 10:48 UTC, cooper-joe approved these changes

2022-12-06 20:03 UTC, eirikhaugstulen reviewed
Hey, @jasminenguyennn!

I notice that the ui is a bit different than what is shown in the design guide. It looks like the picture expects there to be two widgets.
Has the issue changed or is this cleared?

2022-12-07 13:28 UTC, jasminenguyennn commented
> Hey, @jasminenguyennn!
> 
> I notice that the ui is a bit different than what is shown in the design guide. It looks like the picture expects there to be two widgets. Has the issue changed or is this cleared?

good catch @eirikhaugstulen, I update the branch with the suggestion.

2022-12-08 10:34 UTC, eirikhaugstulen approved these changes
Looks good @jasminenguyennn 👍

2022-12-09 13:59 UTC, geethaalwan approved these changes
Tested successfully on 2.40 version

2022-12-13 08:12 UTC, merged