fix: [DHIS2-17054] handle empty expression value
dhis2/capture-app pull request #3635
Opened 2024-05-08 09:54 UTC by simonadomnisoru

[DHIS2-17054](https://dhis2.atlassian.net/browse/DHIS2-17054)

**Tech summary**
- handle empty expression value in `processDisplayKeyValuePair`
- added a unit test for the `undefined` value use case
- small CSS adjustments

2024-05-10 08:33 UTC, superskip reviewed
I found a small simplification, posted as comments. Regarding the css changes, will the bottom margin be constant 0 now? How did it work previously (what does '& + &' mean)?

2024-05-10 08:33 UTC, superskip commented on packages/rules-engine/src/processors/rulesEffectsProcessor/rulesEffectsProcessor.js
> +        const value = data !== undefined ? dataToString(data) : '';
```suggestion
        const data = effect.data || '';
```

2024-05-10 08:33 UTC, superskip commented on packages/rules-engine/src/processors/rulesEffectsProcessor/rulesEffectsProcessor.js
> +                value,
```suggestion
                value: typeof data === 'number' ? numberToString(data) : String(data),
```

2024-05-10 08:45 UTC, superskip commented on packages/rules-engine/src/processors/rulesEffectsProcessor/rulesEffectsProcessor.js
> +        const value = data !== undefined ? dataToString(data) : '';
Hold on, maybe `effect.data` could be `false`.. In that case this won't work.

Revised suggestion:
```suggestion
        const data = effect.data !== undefined ? effect.data : '';
```

2024-05-27 14:13 UTC, simonadomnisoru commented
> I found a small simplification, posted as comments. Regarding the css changes, will the bottom margin be constant 0 now? How did it work previously (what does '& + &' mean)?

Hey,
I applied the small simplifications you suggested. As for the bottom margins, yes, they are all constant now as requested in the ticket. 
From what I understand from [next sibling combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Next-sibling_combinator) and [nesting selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector#appending_the_nesting_selector), `& + &` compiles to `.listItem + .listItem` and matches from the second `.listItem` class until the last one. This means that before the first listItem had a different bottom margin than the second and the rest ones.
Thanks for the feedback!

2024-05-29 13:43 UTC, superskip commented
> From what I understand from [next sibling combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Next-sibling_combinator) and [nesting selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector#appending_the_nesting_selector), & + & compiles to .listItem + .listItem and matches from the second .listItem class until the last one. This means that before the first listItem had a different bottom margin than the second and the rest ones.

Thanks for the explanation :)

@CooperJoe Do you recall what you tried to achieve by using the `& + &` selector?

2024-06-05 11:13 UTC, superskip approved these changes

2024-06-06 08:47 UTC, geethaalwan requested changes
Tested successfully on 2.42,2.41.1,2.40.4,2.39.6 versions

2024-06-06 11:08 UTC, geethaalwan approved these changes

2024-06-06 11:09 UTC, merged